# -*- coding: utf-8 -*-
"""NLTKsummary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YfvxoGVqj4Pcxi5atJI5jRgM9wgHQCzZ
"""

pip install nltk

import nltk
nltk.download('all')
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('corpus')

from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize, sent_tokenize
import bs4 as BeautifulSoup
import urllib.request

#importing libraries


#fetching the content from the URL
fetched_data = urllib.request.urlopen('https://sreekeshiyer.hashnode.dev/getting-started-with-web-development')

def summarize(text: str, per: int) -> str:
    
article_read = fetched_data.read()

#parsing the URL content and storing in a variable
article_parsed = BeautifulSoup.BeautifulSoup(article_read,'html.parser')

#returning <p> tags
paragraphs = article_parsed.find_all('p')

article_content = ''

#looping through the paragraphs and adding them to the variable
for p in paragraphs:  
    article_content += p.text


def _create_dictionary_table(text_string) -> dict:
   
    #removing stop words
    stop_words = set(stopwords.words("english"))
    
    words = word_tokenize(text_string)
    
    #reducing words to their root form
    stem = PorterStemmer()
    
    #creating dictionary for the word frequency table
    frequency_table = dict()
    for wd in words:
        wd = stem.stem(wd)
        if wd in stop_words:
            continue
        if wd in frequency_table:
            frequency_table[wd] += 1
        else:
            frequency_table[wd] = 1

    return frequency_table


def _calculate_sentence_scores(sentences, frequency_table) -> dict:   

    #algorithm for scoring a sentence by its words
    sentence_weight = dict()

    for sentence in sentences:
        sentence_wordcount = (len(word_tokenize(sentence)))
        sentence_wordcount_without_stop_words = 0
        for word_weight in frequency_table:
            if word_weight in sentence.lower():
                sentence_wordcount_without_stop_words += 1
                if sentence[:7] in sentence_weight:
                    sentence_weight[sentence[:7]] += frequency_table[word_weight]
                else:
                    sentence_weight[sentence[:7]] = frequency_table[word_weight]

        sentence_weight[sentence[:7]] = sentence_weight[sentence[:7]] / sentence_wordcount_without_stop_words

       

    return sentence_weight

def _calculate_average_score(sentence_weight) -> int:
   
    #calculating the average score for the sentences
    sum_values = 0
    for entry in sentence_weight:
        sum_values += sentence_weight[entry]

    #getting sentence average value from source text
    average_score = (sum_values / len(sentence_weight))

    return average_score

def _get_article_summary(sentences, sentence_weight, threshold):
    sentence_counter = 0
    article_summary = ''

    for sentence in sentences:
        if sentence[:7] in sentence_weight and sentence_weight[sentence[:7]] >= (threshold):
            article_summary += " " + sentence
            sentence_counter += 1

    return article_summary

def _run_article_summary(article):
    
    #creating a dictionary for the word frequency table
    frequency_table = _create_dictionary_table(article)

    #tokenizing the sentences
    sentences = sent_tokenize(article)

    #algorithm for scoring a sentence by its words
    sentence_scores = _calculate_sentence_scores(sentences, frequency_table)

    #getting the threshold
    threshold = _calculate_average_score(sentence_scores)

    #producing the summary
    article_summary = _get_article_summary(sentences, sentence_scores, 1.5 * threshold)

    return article_summary

if __name__ == '__main__':
    text = """
    The Seattle Center Monorail is an elevated straddle-beam monorail line in Seattle, Washington, United States. The 0.9-mile (1.4 km) monorail runs along 5th Avenue between Seattle Center and Westlake Center in Downtown Seattle, making no intermediate stops. The monorail is a major tourist attraction but also operates as a regular public transit service with trains every ten minutes running for up to 16 hours per day. It was constructed in eight months at a cost of $4.2 million for the 1962 Century 21 Exposition, a world's fair hosted at Seattle Center. The monorail underwent major renovations in 1988 after the southern terminal was moved from its location over Pine Street to inside the Westlake Center shopping mall.

    The system retains its original fleet of two Alweg trains from the world's fair; each carries up to 450 people. It is owned by the city government, which designated the tracks and trains as a historic landmark in 2003. A private contractor has operated the system since 1994, when it replaced King County Metro, the county's public transit system. The monorail carries approximately two million people annually and earns a profit split between the contractor and the city government. The monorail usually operates with one train per track, and the entire trip takes approximately two minutes. Several major accidents have occurred during the system's half-century in service, including a train-to-train collision in 2005 on a gauntlet track near the Westlake Center terminal.

    Several government agencies and private companies have proposed expansions to the monorail system since its inception in the 1960s. The most prominent was the Seattle Monorail Project, founded by a 1997 ballot initiative to build a citywide network that would expand coverage beyond the planned Link light rail system. The project ran into financial difficulties, including cost estimates rising to $11 billion, before being cancelled by a city vote in 2005.
    """
    
    summary_results = _run_article_summary(article_content)
print(summary_results)    
