name: next_actions

on: [push, pull_request]

jobs:
    Lint:
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                working-directory: ./frontend
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14]
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup Node Env
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: ${{ matrix.node }}

            - name: Cache node_modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Install dependencies
              run: npm ci

            - name: Run lint
              run: npm run lint
    Prettier:
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                working-directory: ./frontend
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14]

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup Node Env
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: ${{ matrix.node }}

            - name: Cache node_modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Install dependencies
              run: npm ci

            - name: Run Prettier
              run: npm run style:prettier
